import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { stripTypeScriptTypes } from 'node:module';
const env = { INNERG_GMAIL_WEBHOOK_SECRET: 'test-only-key' };
globalThis.Deno = { env: { get: key => env[key] } };
const helper = stripTypeScriptTypes(await readFile(new URL('./gmail.ts', import.meta.url), 'utf8'));
const { sendGmail } = await import('data:text/javascript;base64,' + Buffer.from(helper).toString('base64'));
const payload = { email: 'test@example.com', memberId: 'TEST-1', firstName: 'member' };
let calls = 0;
const success = async (url, options) => {
  calls++;
  assert.match(url, /^https:\/\/script.google.com\/macros\/s\//);
  assert.equal(JSON.parse(options.body).secret, 'test-only-key');
  assert.equal(options.method, 'POST');
  return Response.json({ ok: true, duplicate: calls > 1 });
};
assert.deepEqual(await sendGmail(payload, success), { ok: true, duplicate: false });
assert.deepEqual(await sendGmail(payload, success), { ok: true, duplicate: true });
await assert.rejects(sendGmail(payload, async () => new Response('error', { status: 500 })), /HTTP 500/);
await assert.rejects(sendGmail(payload, async () => Response.json({ ok: false, error: 'Unauthorized' })), /rejected/);
await assert.rejects(sendGmail(payload, async () => new Response('<html>Login required</html>')), /JSON|Unexpected token/);
await assert.rejects(sendGmail(payload, async () => { throw new Error('Timed out'); }), /Timed out/);
delete env.INNERG_GMAIL_WEBHOOK_SECRET;
await assert.rejects(sendGmail(payload, success), /not configured/);
env.INNERG_GMAIL_WEBHOOK_SECRET = 'test-only-key';
env.INNERG_GMAIL_WEBHOOK_URL = 'https://example.com/';
await assert.rejects(sendGmail(payload, success), /Invalid Gmail endpoint/);
const webhook = await readFile(new URL('./stripe-webhook.ts', import.meta.url), 'utf8');
assert.match(webhook, /constructEventAsync\(rawBody, signature, webhookSecret\)/);
assert.match(webhook, /session.payment_status === "unpaid"/);
assert.match(webhook, /if \(!membership.welcome_email_sent_at\)/);
assert.match(webhook, /getUserById\(userId\)/);
assert.match(webhook, /if \(receiptError\) throw/);
assert.doesNotMatch(webhook, /api.resend.com|RESEND_API_KEY/);
console.log('Connection checks passed: success, duplicate, HTTP error, rejection, non-JSON, timeout, missing key, invalid URL, signed payment and receipt guards.');
